name: HK TrendSetter
analytics: {}
content_rating:
  adult: false
github: true
description: >-
  Our idea of the business would be the new online trader of exclusive or
  customized products where we meet future excess demand by predicting the
  future trend by channeling the supply in advance to get our hands on to-be-hot
  products earlier, providing a fast and efficient one-stop-shop experience to
  our customers and save them from experiencing a complicated and painful
  process and guarantee them the chance to quickly get their hands on the hot
  products.
opengraph: {}
title: HK TrendSetter
author: {}
color:
  lightness: 0.5812342689794568
  brandColors:
    - '#A7304F'
    - '#F46D8D'
    - '#F39EB5'
    - '#081028'
    - '#F0CEB7'
  saturation: 0.9559131411267242
  brandStrength: 0.43768442874720426
  rhythmicContrast: 0.9366100849436154
